// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_EDwFVFHqv75PurBoX30pAmq54Fmz_4',
    appId: '1:54852093651:web:f096b6e206d0afbd493626',
    messagingSenderId: '54852093651',
    projectId: 'way-c20c7',
    authDomain: 'way-c20c7.firebaseapp.com',
    storageBucket: 'way-c20c7.firebasestorage.app',
    measurementId: 'G-P7VBN140BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPP9TgJVWdlBCRdj54FWCwUoBriF-iyk',
    appId: '1:54852093651:android:6db658d840711857493626',
    messagingSenderId: '54852093651',
    projectId: 'way-c20c7',
    storageBucket: 'way-c20c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWKxYykxAkVSgArxxBEiawN35KgtV3js',
    appId: '1:54852093651:ios:45e3d928b9e8f6cb493626',
    messagingSenderId: '54852093651',
    projectId: 'way-c20c7',
    storageBucket: 'way-c20c7.firebasestorage.app',
    iosBundleId: 'com.example.wassly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWKxYykxAkVSgArxxBEiawN35KgtV3js',
    appId: '1:54852093651:ios:45e3d928b9e8f6cb493626',
    messagingSenderId: '54852093651',
    projectId: 'way-c20c7',
    storageBucket: 'way-c20c7.firebasestorage.app',
    iosBundleId: 'com.example.wassly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi_EDwFVFHqv75PurBoX30pAmq54Fmz_4',
    appId: '1:54852093651:web:2ce7bf5cd49cd674493626',
    messagingSenderId: '54852093651',
    projectId: 'way-c20c7',
    authDomain: 'way-c20c7.firebaseapp.com',
    storageBucket: 'way-c20c7.firebasestorage.app',
    measurementId: 'G-HHGD4QSHYZ',
  );
}
